GET http://localhost:3001/api/currency/

GET http://localhost:3001/api/currency/1

POST http://localhost:3001/api/currency
Content-Type: application/json

{
  "id": 4,
  "currencyCode": "GBP",
  "country": "United Kingdom",
  "conversionRate": 0.69
}

PUT http://localhost:3001/api/currency/2/0.8

DELETE http://localhost:3001/api/currency/1
